---
# tasks file for roles/deploy_wordpress
- name: install docker & docker for python
  apt:
    name: docker.io, python3-docker
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "Instanciate wordpress {{ item.name }}"
  include_tasks: wordpress.yml
  with_fileglob:
    - "./group_vars/instances_wordpress/*.yml"
